USE [General Ledger]

SELECT *
FROM GL_JOURNAL_HDR
WHERE TRANS_YEAR = '2018'
AND DOC_SRC = 'JMA67'
AND DOC_NO = 1438

DELETE GL_JOURNAL_HDR
WHERE TRANS_YEAR = '2018'
AND DOC_SRC = 'jma25'
AND DOC_NO = 2586
AND TRANS_STATUS = 'W'
