
SELECT DISTINCT (dba.NO_NPWP_NOTARIS)NO_NPWP,dn.NPWP
		, dba.BY_AKTA_SD_BLN_LALU, dba.KUMULATIF_SD_BLN_LALU
		, BY_AKTA_BLN_INI = CASE when dba.BY_AKTA_TITIPAN  = 0 THEN dba.BY_AKTA_BLN_INI ELSE 0 END
		, KUMULATIF_BLN_INI = CASE when dba.BY_AKTA_TITIPAN = 0 THEN dba.KUMULATIF_BLN_INI ELSE 0 END 
		, PPH_GROSS_BLN_INI = CASE when dba.BY_AKTA_TITIPAN  = 0 THEN dba.PPH_GROSS_BLN_INI ELSE 0 END
		, PPH_REAL_BLN_INI = CASE when dba.BY_AKTA_TITIPAN = 0 THEN dba.PPH_REAL_BLN_INI  ELSE 0 END 
		, dba.PERIODE, dba.NO_NPWP_CBG, (dba.BY_AKTA_TITIPAN)TITIPAN
		, dba.NAMA_NOTARIS,dn.NAMA_NOTARIS--, dbat.JNS_BYR remark by calvin 18/12/15
		, dn.ALAMAT1
		, dn.ALAMAT2
		, dn.KOTA
		, dn.KODEPOS
		, dn.NO_KTP
		, dbat.BRANCH_CODE, dn.BRANCH_CODE --shelly 20160825 
FROM DS_BIAYA_AKTA dba 
INNER JOIN DS_BIAYA_AKTA_TRANSAKSI dbat ON dbat.NO_DATA_BIAYAAKTA = dba.NO_DATA_BIAYAAKTA
INNER JOIN DS_NOTARIS dn ON dn.NO_DATA_NOTARIS = dbat.NO_DATA_NOTARIS
WHERE dba.PERIODE = '201710'
--and dbat.BRANCH_CODE <> dn.BRANCH_CODE
	AND dba.NO_NPWP_CBG = '01.646.678.1-007.000'
ORDER BY dba.NAMA_NOTARIS, dba.NO_NPWP_CBG

select count(NO_DATA_NOTARIS),NO_DATA_NOTARIS
from DS_BIAYA_AKTA_TRANSAKSI
group by NO_DATA_NOTARIS
having count(NO_DATA_NOTARIS) >  1


SELECT *
from DS_BIAYA_AKTA_TRANSAKSI t
inner join DS_BIAYA_AKTA a
on t.NO_DATA_BIAYAAKTA = a.NO_DATA_BIAYAAKTA
where t.NO_DATA_BIAYAAKTA =114

SELECT NPWP, NO_KTP
FROM DS_NOTARIS
WHERE NPWP = NO_KTP

DECLARE @Tgl     AS DATETIME,
		@PERIODE AS NUMERIC(6,0)

SET @PERIODE = 201710
SET @Tgl = dbo.SetJamTgl(
        dbo.SetMonthEndDate(
            CONVERT(
                DATETIME,
                (
                    CONVERT(CHAR, CONVERT(INT, @Periode) % 100) + '/1/' + 
                    CONVERT(CHAR, CONVERT(INT, @Periode) / 100)
                )
            )
        )
    )

SELECT DISTINCT CASE WHEN RIGHT(A.PERIODE,2) >= 10 THEN RIGHT(A.PERIODE,2)
			ELSE RIGHT(A.PERIODE,1)
		END MasaPajak,
		LEFT(A.PERIODE,4) TahunPajak,
		0 AS Pembetulan,
		'' AS NoBuktiPotong,
		N.NPWP AS NPWP_WP,
		N.NO_KTP AS KTP_WP,
		N.NAMA_NOTARIS AS Nama_WP,
		N.ALAMAT1 AS Alamat_WP,
		'N' AS fWNA,
		'' AS KodeNegara,
		'21-100-07' AS KodePajak,
		A.KUMULATIF_BLN_INI * 2 AS JumlahBruto,
		A.KUMULATIF_BLN_INI AS JumlahDPP,
		CASE WHEN LEN(REPLACE(REPLACE(REPLACE(REPLACE(N.NPWP,'.',''),'-',''),' ',''),',','')) = 15 THEN 'N'
			 ELSE 'Y'
		END fTanpaNPWP,
		CASE WHEN A.KUMULATIF_SD_BLN_LALU >= 0 AND A.KUMULATIF_SD_BLN_LALU <= 50000000 THEN 5
			 WHEN A.KUMULATIF_SD_BLN_LALU > 50000000 AND A.KUMULATIF_SD_BLN_LALU <= 250000000 THEN 15
			 WHEN A.KUMULATIF_SD_BLN_LALU > 250000000 AND A.KUMULATIF_SD_BLN_LALU <= 500000000 THEN 25
			 WHEN A.KUMULATIF_SD_BLN_LALU > 500000000 THEN 30
		END Rate,
		A.PPH_REAL_BLN_INI AS JumlahPPH,
		A.NO_NPWP_CBG AS NPWPPemotong,
		'PT INDOMOBIL FINANCE INDONESIA' AS NamaPemotong,
		@Tgl AS TglBuktiPotong,
		'' AS KodeForm,
		'' AS KodeJasa,
		'PPH21' AS JenisPajak,
		N.BRANCH_CODE AS KodeCabang,
		'' AS Inisial,
		1 AS fDS,
		'' AS NoBuktiPotongHdr
FROM DS_BIAYA_AKTA A 
INNER JOIN DS_BIAYA_AKTA_TRANSAKSI T 
ON A.NO_DATA_BIAYAAKTA = T.NO_DATA_BIAYAAKTA
INNER JOIN DS_NOTARIS N 
ON N.NO_DATA_NOTARIS = T.NO_DATA_NOTARIS
WHERE A.PERIODE = @PERIODE
AND A.NO_NPWP_CBG = '01.646.678.1-007.000'


SELECT NO_NPWP_CBG , T.BRANCH_CODE
FROM DS_BIAYA_AKTA A 
INNER JOIN DS_BIAYA_AKTA_TRANSAKSI T 
ON A.NO_DATA_BIAYAAKTA = T.NO_DATA_BIAYAAKTA



